### ISSUE TITLE
My Services

### ISSUE THREAD

**Issue by Saul3d** [wchipchase/clinkedin#3]
### User Story
As a ClinkedIn member, I want to list my services so that other inmates can ask me for help

### AC
**Given**  that I am a ClickedIn member and I have a service to offer
**When** When other inmates want my services
**Then** they should have a view a list of my services

### Development

- Need to create a list of services
- Create an endpoint for services
- Create a get method in our ClinkedIn Repository

**Comment by wchipchase** [comment]
👍
